version: "3.9"
services:
  main:
    image: main:latest
    build:
      context: .
      dockerfile: Dockerfile
  ## server service
  server:
    image: server:latest
    ports:
      - 5000:5000
    build:
      context: .
      dockerfile: Dockerfile
      target: server
  admin-console:
    image: admin-console:latest
    ports:
      - 80:80
    build:
      context: .
      dockerfile: Dockerfile
      target: admin-console
  ## database service
  db:
    image: postgres:14.1-alpine
    # restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - oauth-server-data:/var/lib/postgresql/data
volumes:
  oauth-server-data:
